/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ienning_ndktest_Testso */

#ifndef _Included_com_example_ienning_ndktest_Testso
#define _Included_com_example_ienning_ndktest_Testso
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ienning_ndktest_Testso
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ienning_ndktest_Testso_get
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ienning_ndktest_Testso
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ienning_ndktest_Testso_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
